### ISSUE TITLE
DeserializationError in getSchedule

### ISSUE THREAD

**Issue by moepoi** [javoeria/jikan-dart#1]
> DeserializationError (Deserializing '[request_hash, request:schedule:8afa3ba4218f1b668cd1e15205fc3f8e7a861bc3, req...' to 'Schedule' failed due to: Deserializing '[{mal_id: 38843, url: https://myanimelist.net/anime/38843/Shironeko_Project__...' to 'BuiltList<AnimeItem>' failed due to: Deserializing '[mal_id, 41522, url, https://myanimelist.net/anime/41522/Washimo_8th_Season, ...' to 'AnimeItem' failed due to: Tried to construct class "AnimeItem" with null field "synopsis". This is forbidden; to allow it, mark "synopsis" with @nullable.)

- https://api.jikan.moe/v3/schedule/monday

**Comment by javrosales** [comment]
Hello, I just released a new version 1.3.1 that fixes the synopsis field.
Currently, the Jikan API is having trouble connecting to MyAnimeList, so it is likely that you will have some issues getting the data.
Thanks for using the package! 😄
