### ISSUE TITLE
Favorites empty

### ISSUE THREAD

**Issue by riccardocescon** [javoeria/jikan-dart#4]
There is an issue with Favorites, i always get 0 favorite on anime, manga, characters and people.
How i get user profile : 
`_user = await jikan.getUserProfile(user.name);`
Then i get the Favorites by : 
`Favorites favs = _user.favorites;`

Is there a problem or i did something wrong?
Thanks in advance

**Comment by javrosales** [comment]
Hi, this problem is from the jikan server and not related to the package.
There is an open issue about this: jikan-me/jikan#374

**Comment by riccardocescon** [comment]
Oh i see, then i'm going to close this issue. Thank you
