### ISSUE TITLE
Migrate to v4

### ISSUE THREAD

**Issue by ikramhasan** [javoeria/jikan-dart#6]
The v3 API that the package is using is now discontinued. It is recommended to migrate to v4.

**Comment by javrosales** [comment]
Hi, sorry for the delay, I just uploaded a new version 2.0.0 with the migration to v4 😄

**Comment by ikramhasan** [comment]
Awesome! I made an app using your API. Here's the link if you're interested: https://play.google.com/store/apps/details?id=com.ikramhasan.anime_portal

This project also inspired me to write my own API for comic books and release it in pub.dev. Thanks a lot for the inspiration.
