### ISSUE TITLE
Error Deserializing

### ISSUE THREAD

**Issue by dheerajbred** [javoeria/jikan-dart#7]
Getting this error for multiple functions
jikan.getAnimeEpisodes(myID)
![image](https://user-images.githubusercontent.com/46578244/224475197-12e4d163-9e37-45e3-ae88-19ca1204de59.png)
Even tried locally changing url as @nullable. Still doesn't work
![image](https://user-images.githubusercontent.com/46578244/224475217-989d4d64-15dc-44c2-bea7-a43cf93aaa13.png)

**Comment by dheerajbred** [comment]
```
var animePidctures = await jikan.getAnimeEpisodes(49918);
print("----------jikan-------animePidctures: $animePidctures");
```
This is my code
getAnimeReviews() and other functions also same error

**Comment by javrosales** [comment]
Hi, I just uploaded a new version 2.1.0 that fixes it.
Thanks for using the package! 😄
