### ISSUE TITLE
Connection Failed Issue

### ISSUE THREAD

**Issue by Lastmentor** [javoeria/jikan-dart#8]
When I run the code below it's giving me a **Connection Failed**
It was working fine 2-3 weeks ago, I just want to let you guys know about this.

```
var jikan = Jikan();
var top = await jikan.getTopAnime(type: TopType.tv, filter: TopFilter.airing);
print(top);
```

**Error:**
Unhandled Exception: Connection failed
E/flutter (24928): #0      IOClient.send (package:http/src/io_client.dart:88:7)
E/flutter (24928): <asynchronous suspension>
E/flutter (24928): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
E/flutter (24928): <asynchronous suspension>
E/flutter (24928): #2      _withClient (package:http/http.dart:164:12)
E/flutter (24928): <asynchronous suspension>
E/flutter (24928): #3      Jikan._getResponse (package:jikan_api/src/jikan.dart:42:18)
E/flutter (24928): <asynchronous suspension>
E/flutter (24928): #4      Jikan.getTopAnime (package:jikan_api/src/jikan.dart:377:20)
E/flutter (24928): <asynchronous suspension>
E/flutter (24928): #5      _MyHomePageState._incrementCounter (package:exit/main.dart:56:15)
E/flutter (24928): <asynchronous suspension>

**Comment by javrosales** [comment]
Hi, it works for me with the latest version.
https://api.jikan.moe/v4/top/anime?page=1&type=tv&filter=airing
